apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wooden-cow-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wooden-cow-go 
  name: wooden-cow-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wooden-cow-go 
